language: node_js
services: mongodb
node_js:
- '0.10'
script:
  - npm test
  - npm run-script lint
env:
  global:
    - PROVIDER_URL="http://localhost:8000"
    - ANYFETCH_API_ID="ANYFETCH-ID"
    - ANYFETCH_API_SECRET="ANYFETCH-SECRET"
